export { default as NoImage } from "./no-image.jpg"
export { default as AvatarDefault } from "./avatar-default.png"
export { default as RentallyLogo } from "./rentally_logo.png"
export { default as RentallyLogoFull } from "./rentally_logo_full.png"
export { default as Empty } from "./box.png"
