export { default as Login } from "@/pages/public/Login"
export { default as Register } from "@/pages/public/Register"
export { default as ForgotPassword } from "@/pages/public/ForgotPassword"
export { default as ResetPassword } from "@/pages/public/ResetPassword"
export { default as Account } from "@/pages/public/Account"
